var color= "red";
if (color== "red")
{
    console.log("STOP");
}
if (color== "Yellow")
{
    console.log("get ready");
}
if (color== "green")
{
    console.log("Go");
}

console.log("---------------");

var season = "spring";
if (season== "spring")
{
    console.log("Enjoy the blowing flowers");
}
if (season== "winter")
{
    console.log("bundle up warm stay warm");
}
if (season== "summer")
{
    console.log("have fun in the sun");
}
if (season== "autumn")
{
    console.log("admire the colorful leaves");
}
